version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - REACT_APP_API_URL=https://js-project-backend.onrender.com/
    image: alexiej123/js-project:frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - REACT_APP_API_URL=https://js-project-backend.onrender.com/
    image: alexiej123/js-project:nginx
    ports:
      - "80:3000"
    depends_on:
      - app
